#!/bin/sh
# luci-app-fcc — translation catalogue generator.
#
# Scans the LuCI views and the browser scripts for translatable strings and
# (re)writes po/templates/fcc.pot. Existing po/<lang>/fcc.po files are then
# refreshed with msgmerge when it is available; otherwise they are left alone
# and only new msgids are reported, so this script never destroys a translation.
#
# Recognised forms:
#   views  <%:Some text%>          LuCI translate tag
#   views  <%:Some text%>          (same, with %s/%d placeholders)
#   js     FCC._('Some text')      client-side translate helper
#   js     FCC._("Some text")
#
# Usage: scripts/gen-po.sh [--check]
#   --check   exit 1 if po/templates/fcc.pot is out of date (for CI)

set -eu

SELF_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
ROOT=$(CDPATH= cd -- "$SELF_DIR/.." && pwd)
POT="$ROOT/po/templates/fcc.pot"
VIEWS="$ROOT/luasrc/view/fcc"
JS="$ROOT/htdocs/luci-static/resources/fcc"

CHECK=0
[ "${1:-}" = "--check" ] && CHECK=1

tmp=$(mktemp) || exit 1
trap 'rm -f "$tmp"' EXIT INT TERM

# --- collect msgids ---------------------------------------------------------
# grep -o, not sed s///: a line such as
#   FCC.el('td', { text: a.running ? FCC._('running') : FCC._('stopped') })
# carries two strings, and a greedy `.*` would keep only the last one. Every
# string in this package is a single line of plain text with no embedded quotes,
# so no unescaping is needed.
{
	for f in "$VIEWS"/*.htm; do
		[ -f "$f" ] || continue
		grep -o '<%:[^%]*%>' "$f" | sed 's/^<%://; s/%>$//'
	done
	for f in "$JS"/*.js; do
		[ -f "$f" ] || continue
		grep -o "FCC\._('[^']*')" "$f" | sed "s/^FCC\._('//; s/')$//"
		grep -o 'FCC\._("[^"]*")' "$f" | sed 's/^FCC\._("//; s/")$//'
	done
} | sed 's/^[[:space:]]*//; s/[[:space:]]*$//' | grep -v '^$' | LC_ALL=C sort -u > "$tmp"

# --- emit -------------------------------------------------------------------
emit() {
	cat <<'EOF'
# luci-app-fcc translation template.
# Copyright (C) 2026 Arthur97172
# This file is distributed under the same license as the luci-app-fcc package.
#
# Generated by scripts/gen-po.sh — do not edit by hand.
#
msgid ""
msgstr ""
"Project-Id-Version: luci-app-fcc\n"
"Report-Msgid-Bugs-To: https://github.com/Arthur97172/luci-app-fcc/issues\n"
"POT-Creation-Date: 2026-10-02 00:00+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"
EOF
	while IFS= read -r line; do
		printf '\nmsgid "%s"\nmsgstr ""\n' "$line"
	done < "$tmp"
}

if [ "$CHECK" = 1 ]; then
	emit > "$tmp.new"
	if cmp -s "$tmp.new" "$POT"; then
		rm -f "$tmp.new"
		echo "po/templates/fcc.pot is up to date"
		exit 0
	fi
	rm -f "$tmp.new"
	echo "po/templates/fcc.pot is OUT OF DATE — run scripts/gen-po.sh" >&2
	exit 1
fi

mkdir -p "$(dirname -- "$POT")"
emit > "$POT"
echo "wrote $POT ($(wc -l < "$tmp" | tr -d ' ') messages)"

# --- refresh existing translations -----------------------------------------
if command -v msgmerge >/dev/null 2>&1; then
	for po in "$ROOT"/po/*/fcc.po; do
		[ -f "$po" ] || continue
		msgmerge --quiet --update --backup=none "$po" "$POT"
		echo "updated $po"
	done
else
	echo "msgmerge not found — existing .po files were left untouched" >&2
fi
